In [5]:
import pandas as pd
data = pd.read_csv("./data/data1.csv", delimiter=',', index_col='Object')
coords = data.drop('Cluster', axis=1)

In [6]:
from sklearn.cluster import KMeans
import numpy as np
centroid = np.array([[8.5, 8.75], [10.5, 7.13], [12.0, 5.0]])
k_means = KMeans(n_clusters=3, init=centroid, max_iter=100, n_init=1)
model = k_means.fit(coords)
# вывод назначенных кластеров
obj_to_cluster = model.labels_.tolist()
print(obj_to_cluster)

[0, 0, 2, 0, 1, 2, 2, 0, 2, 1, 1, 2, 2, 0, 2]


In [7]:
all_distances = k_means.fit_transform(coords)
print(all_distances)

[[ 3.73630834 10.9188929  14.59661689]
 [ 6.02992537  6.47216261  8.49729849]
 [12.44829306  5.67646212  5.16068339]
 [ 2.0880613   6.87184271 10.3746158 ]
 [ 8.77268488  1.49071198  2.68404203]
 [14.7566934   7.45355992  4.87601376]
 [15.84171708  8.49836586  4.63570878]
 [ 3.28024389 10.67187373 14.54759956]
 [10.89770618  3.72677996  0.45175395]
 [ 6.70522185  2.74873708  6.5293685 ]
 [ 7.4404301   1.88561808  3.97183965]
 [10.09752445  6.87184271  6.34066886]
 [ 9.65194281  3.34995854  2.18529408]
 [ 8.93084542  9.80929265 13.42933129]
 [ 9.62081078  4.92160769  4.18208033]]


In [8]:
# 8.045 - false
# Определить среднее расстояний между объектами и центроидом, отнесенных к кластеру 0.
avg = 0.0
count = 0.0
for i in range(14):
    if obj_to_cluster[i] == 0:
        avg += all_distances[i][0]
        count += 1
print(avg / count)


4.813076866197264
